### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Altamash347** [alperdrsnn/BedWars#1]
### Spawners
- Diamond
- Emerald
- Gold
- Iron
### Shop
- Same as Hypixel but if any items are bugged in that shop, just remove them and try fix them later.
### Others
- Win Rewards by giving money and items
- Spectator Mode
- Scoreboards

I hope you will check this and will try to use my ideas, I am so glad that you are making a bedwars plugin.

**Comment by alperdrsnn** [comment]
I will definitely add your wishes. Actually I also need ideas to improve the plugin. You can write your requests to me on discord. Thanks for suggestions.

**Comment by Altamash347** [comment]
No Problem and Thanks for quick Response
